version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VARIANT: "6.0"
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace
    command: sleep infinity
    network_mode: service:web

  web:
    image: nginx:1.23.1
    volumes:
      - ../frontend/build:/usr/share/nginx/html
      - ./nginx:/etc/nginx
    restart: unless-stopped